POST https://backend-eosin-phi.vercel.app/login HTTP/1.1
content-type: application/json

{
    "email": "adm@sitesdigitais.com",
    "password": "123456"
}

GET https://backend-eosin-phi.vercel.app/users HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbUBzaXRlc2RpZ2l0YWlzLmNvbSIsImlhdCI6MTcyMjA0MTYwNSwiZXhwIjoxNzIyMDQ1MjA1LCJzdWIiOiIzIn0.Z-MCf57VvIRVB9eY2DQOOlc-uNT7_SnmiH9EeL8sJHE


